
# Appendix

Vernon kept some notes at the back of his journal so he wouldn't forget important details about people... or simply so he wouldn't forget why they were in his journal. Regardless of the reason, they are included here.

```{r functions}
set_player <- function(player,
                       character,
                       notes){
  list("Player" = player,
       "Character" = character,
       "Notes" = notes)
}

set_npc <- function(name,
                    notes){
  list("Name" = name,
       "Notes" = notes)
}

```

## PCs 
```{r player_stats}
willy <- set_player(player = "Willy",
                    character = "Vernon Vickies, verdan warlock",
                    notes = "Hates corrupt nobles.  
                    Likes helping people in need.   
                    Has a pact with a demon that demands killing in exchange for not devouring his soul. The demon also bestows magical powers.  
                    Can potentially change gender when attributes change.")

alex <- set_player(player = "Alex",
                   character = "Gilberto, human rogue",
                   notes = "Weak stomach around gore. Strong opinions.")

fetwi <- set_player(player = "Fetwi",
                    character = "Zakham Ruhle, human bard",
                    notes = "A bit silly. Very helpful.")

phil <- set_player(player = "Phil",
                   character = "Dezo the Walker, druid",
                   notes = "Calm, inquisitive.")

mohamed <- set_player(player = "Mohamed",
                      character = "Verril, barbarian",
                      notes = "Pretty dumb but has a good heart. Does whatever he feels like without any thought of consequences. And I thought I was rash sometimes...")

andrei <- set_player(player = "Andrei",
                      character = "Iankul Duskwalker, archer, elf",
                      notes = "Found in a slaver wagon, kind of like me. Seems like a reliable fellow.")

player_stats <- Reduce(dplyr::bind_rows, list(willy, alex, fetwi, phil, mohamed, andrei))

knitr::kable(player_stats) %>% 
  kable_styling("striped", full_width = FALSE) 
```


## NPCs
```{r npc}
Reduce(dplyr::bind_rows, 
       list(set_npc(name = "Vawen Lowwe'elai",
                    notes = "In my original party. Elf woman. Broke her leg in the carriage carnage. Needs help moving, being carried by Prince Darrendil. Was ritualistically murdered while we slept. The killer is unknown, as is the motivation for the murder."),
            set_npc("Dorn Ironskull",
                    "In my original party. Dwarf fighter. Lost conciousness in the carriage carnage from a head wound. Doesn't talk much. Something happeend between him and Gilberto in the fog, but he doesn't seem to be holding a grudge. Trudging along not saying much, but carrying his own weight."),
            set_npc("Tav Torin",
                    "In my original party. Half elf mage. Decapitated during the carriage carnage."),
            set_npc("Prince Darrendil",
                    "Huge and strong. Apparently an elven prince that got turned into a quaggoth. Seems intelligent and polite. He carryied Vawen because of her leg, without complaint. Seemed like a good fellow. Goes into a rage in battle. After we fought the fungus-undead things he went berserk and ran ahead. He ended up fighting a bunch of drow and died. We don't know why he went crazy. It's definitely a loss for the party."),
            set_npc("Neznar",
                    "Drow male who was also a prisoner. The party helped him escape so he is helping them get where they need to go. Doesn't say a lot. Wanted us to get rid of Vawen because \"she's a liability\". He has a mark on the side of his head that looks like a series of moles or some kind of infection that was left untreated, I'm not sure - he claims it's a birthmark. He also mutters to himself a lot. I can't tell if he's a bit unhinged or just odd. I believe him when he sas he will take us where we're going, Neverlight Grove. I believe him when he says he didn't kill Vawyn, it doens't seem like something he would do, but if he's unhinged/infected, who knows what might be affecting him or taking control when he's not aware? He's good in a fight so I hope he's on our side..."),
            set_npc("Stoop",
                    "A miconid (looks like a mushroom) that can communicate telepathically with the party. It seems very friendly and we are trying to bring it home to Neverlight Grove, in the underdark. I don't know where it came from but it sounds like it was 'born' recently in the drow camp."),
            set_npc("Boopido",
                    "An old gnome that always seems scared or surprised. He was a prisoner and escaped with my new friends. My patron wanted me to kill him or Vawyn (I think). In our first battle he ran and hid. I don't trust him, but that's probably what my patron wants...so should I trust him? He's scared of me and definitely doesn't trust me, so it doens't really matter I guess. **Update**: that bloody asshole was the murderder. We avenged our friends and took him down."),
            set_npc("Yuk Yuk",
                    "The shorter of the two goblin guides helping us cross the Silken Paths. Upbeat, friendly, fond of shiny things. A very aggreeable goblin. Knows the webs well and I find myself trusting him easily"),
            set_npc("Spider Bait",
                    "The taller of the two goblin guides helping us cross the Silken Paths. Tall for a goblin but still only about shoulder height on me. He is a stark contrast to his companion. He talks slowly in a monotone voice and dressly much more plainly, with only a single plain earing for jewelry. Despite his somewhat morose demeanor I enjoy his company and find myself trusing him easily."),
            set_npc("Fargas Rumblefoot",
                    "He was crossing the webs with Yuk Yuk and Spider Bait when he got caught by some spiders. We freed him while looting some cocoons we came accross. He seems excitable but that may have just been the circumstances. He seems to have lost an item of importance. We need to find out more about this fellow."),
            set_npc("Errug",
                    "An old garnled halfing-dwarf wizard. He's shifty and clever but not a bad bloke."))) %>% 
  knitr::kable() %>% 
  kable_styling("striped", full_width = FALSE) 

# npc_list <- Reduce(dplyr::bind_rows, list())

# knitr::kable(npc_list) %>% 
# kable_styling("striped", full_width = FALSE) %>% 
# column_spec(7, width_min = "30em") %>% 
# scroll_box(width = "100%")
```
